#!/bin/sh

PATH=$PATH:/usr/bin
LOGPATH=/JOB/log
SHELLNAME=SMICFoundryWipj
EXE_PATH="/JOB/java/WIP/SMIC"

#### For Java Config ####
JAVA_HOME=/usr/java/jdk1.5.0_22
export JAVA_HOME
PATH=$JAVA_HOME/bin:$PATH
export PATH
CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/jre/lib/rt.jar
export CLASSPATH
MEM_ARGS="-Xms64m -Xmx128m"
JAVA_EXE="bin/java"
JAVA_RUN="${JAVA_HOME}/${JAVA_EXE} ${MEM_ARGS} "

EXE_CLASSPATH="./WipLoader.jar:./lib/activation.jar:./lib/c3p0-0.9.1.2.jar:./lib/commons-collections.jar:./lib/commons-lang-2.4.jar:./lib/commons-logging-1.1.1.jar:./lib/commons-net-2.0.jar:./lib/jakarta-oro-2.0.8.jar:./lib/log4j-1.2.15.jar:./lib/mail.jar:./lib/ojdbc5.jar:./lib/poi-2.5.1.jar:./lib/quartz-1.6.5.jar:./lib/spring.jar"

cd ${EXE_PATH}/

echo "$SHELLNAME start on `date`"  >> $LOGPATH/$SHELLNAME.log


${JAVA_RUN} -classpath ${CLASSPATH}:${EXE_CLASSPATH} com.cista.wip.loader.SMICWipParser /JOB/java/WIP/SMIC/REPORT/ /JOB/java/WIP/SMIC/REPORT/ /JOB/java/WIP/SMIC/ERROR/

echo "$SHELLNAME end on `date`"  >> $LOGPATH/$SHELLNAME.log
